app/home/forms.py
# -*- coding: utf-8 -*-

app/home/__init__.py
# -*- coding: utf-8 -*-
from flask import Blueprint

home = Blueprint('home', __name__)


import app.home.views

app/home/views.py
# -*- coding: utf-8 -*-
from datetime import datetime

from flask import render_template, request, jsonify, redirect, url_for

from app import db
from app.home import home
from app.models import Comment, GuestBook
from app.utils.app_utils import get_image
from app.models import Article, AccessLog


# 首页
@home.route('/')
def index():
    page = request.args.get('page', 1)
    all_articles = Article.query.order_by(Article.add_time.desc())
    all_articles = all_articles.paginate(page=int(page), per_page=5)
    ip = request.remote_addr
    log = AccessLog(ip=ip)
    db.session.add(log)
    db.session.commit()

    return render_template('home/index.html', all_articles=all_articles)


# 文章详情
@home.route('/detail')
def detail():
    id = request.args.get('article', '')
    if id:
        article = Article.query.filter_by(id=int(id)).first()
        article.click_nums += 1
        db.session.add(article)
        db.session.commit()
        prev_article = Article.query.filter_by(id=int(id)+1).first()
        next_article = Article.query.filter_by(id=int(id)-1).first()

        all_comments = Comment.query.filter_by(article_id=article.id).order_by(Comment.add_time.desc())
        comment_nums = all_comments.count()


        return render_template(
            'home/detail.html', article=article, prev_article=prev_article,
            next_article=next_article, all_comments=all_comments,
            comment_nums=comment_nums
        )
    return redirect(url_for('home.index'))


# 留言页面
@home.route('/leavemsg')
def leave_msg():
    page = request.args.get('page', 1)
    all_comments = GuestBook.query.order_by(GuestBook.add_time.desc())
    comment_nums = all_comments.count()
    # 分页
    all_comments = all_comments.paginate(page=int(page), per_page=10)
    return render_template(
        'home/gustbook.html', all_comments=all_comments,comment_nums=comment_nums
    )


# 添加评论/留言
@home.route('/addcomment', methods=['GET', 'POST'])
def add_comment():
    article_id = request.values.get('article_id','')
    nick_name = request.values['author']
    email = request.values['email']
    content = request.values['comment']
    head_image = get_image()
    strtime = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    # 添加评论
    if article_id:
        article = Article.query.filter_by(id=int(article_id)).first()
        comment = Comment(
            nick_name=nick_name, email=email, content=content, head_image=head_image,
            article_id = article.id
        )

        if article:
            db.session.add(comment)
            db.session.commit()

            return jsonify({'code': 1, 'head_image': head_image, 'strtime':strtime})
        return jsonify({'code': 2, 'msg':'评论失败'})
    # 添加留言
    guest_book = GuestBook(
        nick_name=nick_name, email=email, content=content, head_image=head_image,
    )
    db.session.add(guest_book)
    db.session.commit()
    return jsonify({'code':1, 'head_image':head_image, 'strtime':strtime})


app/templates/home/base.html
<!DOCTYPE html>
<html lang="zh">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>{% block title %}Panson的博客{% endblock %}</title>
    <meta name="description" content=""/>
    <meta name="keywords" content=""/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/index.css') }}" media="all"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/page/style.css') }}" media="all" />

    {% block css %} {% endblock %}

</head>

<body class="home blog custom-background round-avatars">
<div class="Yarn_Background"
     style="background-image: url( {{ url_for("static", filename="images/47fb3c_.jpg") }});"></div>

<div class="navi" data-aos="fade-down">

    <div class="navbar animated fadeInRight">
        <div class="inner">
            <nav id="site-navigation" class="main-navigation">
                <div id="main-menu" class="main-menu-container">
                    <div class="menu-menu-container">
                        <ul id="primary-menu" class="menu">
                            <li id="menu-item-17"
                                class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-17">
                                <a href="{{ url_for('home.index') }}">首页</a>
                            </li>

                            <li id="menu-item-57"
                                class="menu-item menu-item-type-post_type menu-item-object-page menu-item-57">
                                <a href="{{ url_for('home.leave_msg') }}">留言</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
{#            <!-- #site-navigation -->#}
        </div>
    </div>
</div>

<header id="masthead" class="overlay animated from-bottom" itemprop="brand">
    <div class="site-branding text-center">
        <a href="">
            <figure>
                <img class="custom-logo avatar"
                     src="{{ url_for('static', filename='images/d9885b7dc7a78f9cadfb81be7512d630.png') }}"/>
            </figure>
        </a>
        <h2 class="blog-description"><p>Panson 个人博客</p></h2>
    </div>
    <!-- .site-branding -->
    <div class="decor-part">
        <div id="particles-js"></div>
    </div>
    <div class="animation-header">
        <div class="decor-wrapper">
            <svg id="header-decor" class="decor bottom" xmlns="http://www.w3.org/2000/svg" version="1.1"
                 viewBox="0 0 100 100" preserveAspectRatio="none">
                <path class="large left" d="M0 0 L50 50 L0 100" fill="rgba(255,255,255, .1)"></path>
                <path class="large right" d="M100 0 L50 50 L100 100" fill="rgba(255,255,255, .1)"></path>
                <path class="medium left" d="M0 100 L50 50 L0 33.3" fill="rgba(255,255,255, .3)"></path>
                <path class="medium right" d="M100 100 L50 50 L100 33.3" fill="rgba(255,255,255, .3)"></path>
                <path class="small left" d="M0 100 L50 50 L0 66.6" fill="rgba(255,255,255, .5)"></path>
                <path class="small right" d="M100 100 L50 50 L100 66.6" fill="rgba(255,255,255, .5)"></path>
                <path d="M0 99.9 L50 49.9 L100 99.9 L0 99.9" fill="rgba(255,255,255, 1)"></path>
                <path d="M48 52 L50 49 L52 52 L48 52" fill="rgba(255,255,255, 1)"></path>
            </svg>
        </div>
    </div>
</header>

{% block content %}

{% endblock %}

<footer id="footer" class="overlay animated from-top">
    <div class="decor-wrapper">
        <svg id="footer-decor" class="decor top" xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 100 100"
             preserveAspectRatio="none">
            <path class="large left" d="M0 0 L50 50 L0 100" fill="rgba(255,255,255, .1)"></path>
            <path class="large right" d="M100 0 L50 50 L100 100" fill="rgba(255,255,255, .1)"></path>
            <path class="medium left" d="M0 0 L50 50 L0 66.6" fill="rgba(255,255,255, .3)"></path>
            <path class="medium right" d="M100 0 L50 50 L100 66.6" fill="rgba(255,255,255, .3)"></path>
            <path class="small left" d="M0 0 L50 50 L0 33.3" fill="rgba(255,255,255, .5)"></path>
            <path class="small right" d="M100 0 L50 50 L100 33.3" fill="rgba(255,255,255, .5)"></path>
            <path d="M0 0 L50 50 L100 0 L0 0" fill="rgba(255,255,255, 1)"></path>
            <path d="M48 48 L50 51 L52 48 L48 48" fill="rgba(255,255,255, 1)"></path>
        </svg>
    </div>
    <div class="socialize" data-aos="zoom-in">

        <li class="wechat">
            <a class="socialicon"><i class="iconfont">&#xe609;</i></a>
            <div class="wechatimg"><img src="{{ url_for('static', filename='images/IMG_1415(20180923-171549).jpg') }}"></div>
        </li>

    </div>
    <div class="cr">
        Copyright&copy;2018. Design by Panson

    </div>
</footer>
<script type='text/javascript' src='{{ url_for("static", filename="js/jquery.min.js") }}'></script>
<script type='text/javascript' src='{{ url_for("static", filename="js/plugins.js") }}'></script>
<script type='text/javascript' src='{{ url_for("static", filename="js/script.js") }}'></script>
<script type='text/javascript' src='{{ url_for("static", filename="js/particles.js") }}'></script>
<script type='text/javascript' src='{{ url_for("static", filename="js/aos.js") }}'></script>
<script type='text/javascript' src='{{ url_for("static", filename="js/comments-ajax.js") }}'></script>
<script type='text/javascript' src='{{ url_for("static", filename="js/form.js") }}'></script>
<script>
    var pagnation = $("#pagnation");
    $(document).on("keydown", function (event) {
        switch (event.keyCode) {
            case 37 :
                window.location.href = pagnation.find(".page-prev").attr("href");
                break;
            case 39 :
                window.location.href = pagnation.find(".page-next").attr("href");
                break
        }
    });
</script>

</body>

</html>

app/templates/home/detail.html
{% extends "home/base.html" %}
{% import 'utils_template/page.html' as home_page %}
{% block title %}
    文章详情 - Panson的博客
{% endblock %}

{% block content %}
    <div id="main" class="content">
        <div class="container">
            <article id="post-1202"
                     class="js-gallery post-1202 post type-post status-publish format-standard has-post-thumbnail hentry category-uncategorized tag-11 tag-22 tag-29">
                <style>
                    .container {
                        padding: 10px 0px;
                    }

                    .post {
                        margin: 0 auto
                    }
                </style>
                <section class="post_content">
                    <header class="post_header">
                        <h1 class="post_title">{{ article.title }}</h1>
                        <time datetime="{{ article.add_time }}">{{ article.add_time }}发布&nbsp;&nbsp;&nbsp;浏览: {{ article.click_nums }}</time>
                    </header>
                    <div class="post-body js-gallery" style="color: black;">
                        {{ article.content|safe }}
                    </div>
                    <div class="meta split split--responsive cf">

                        <div class="slide">
                            <a class="btn-slide" title="switch down"><i class="iconfont">&#xe615;</i>折叠评论区</a>
                        </div>
                    </div>
                </section>
            </article>
        </div>
        <svg id="upTriangleColor" width="100%" height="40" viewBox="0 0 100 102" preserveAspectRatio="none">
            <path d="M0 0 L50 100 L100 0 Z"></path>
        </svg>
        <div id="social">
            <ul>
                <li>
                    <a href="" title="qzone" target="_blank"><i class="iconfont">&#xe67f;</i></a>
                </li>
                <li>
                    <a href="" title="weibo" target="_blank"><i class="iconfont">&#xe680;</i></a>
                </li>
                <li>
                    <a href="" title="douban" target="_blank"><i class="iconfont">&#xe681;</i></a>
                </li>
                <li>
                    <a href="" title="twitter" target="_blank"><i class="iconfont">&#xe683;</i></a>
                </li>
            </ul>
        </div>
        <div id="panel">
            <div class="comment-area">
                <section class="comments">
                    <div class="comments-main" id="load_comment">

                        <div id="respond" class="comment-respond">
                            <h6 id="replytitle" class="comment-reply-title"><a rel="nofollow"
                                                                               id="cancel-comment-reply-link" href=""
                                                                               style="display:none;">取消</a></h6>
                            <form action="#" method="post" id="commentform" class="clearfix">
                                <div class="clearfix"></div>
                                <div class="author-info">
                                    <input type="text" name="author" id="author" placeholder="昵  称 : " value=""
                                           tabindex="1" title="Name (required)" required/>
                                    <input type="email" name="email" id="email" placeholder="邮  箱 : " value=""
                                           tabindex="2" title="E-mail(will not be published) required" required/>
                                </div>
                                <div class="clearfix"></div>
                                 <input type='hidden' name='article_id' value='{{ article.id }}' id="article_id"/>
                                <input type='hidden' name='comment_post_ID' value='2' id='comment_post_ID'/>
                                <input type='hidden' name='comment_parent' id='comment_parent' value='0'/>
                                <p style="display: none;"><input type="hidden" id="akismet_comment_nonce"
                                                                 name="akismet_comment_nonce" value="44ac0661b8"/></p>
                                <p style="display: none;"><input type="hidden" id="ak_js" name="ak_js" value="105"/></p>
                                <div class="comment-form-info">
                                    <div class="real-time-gravatar"><img id="real-time-gravatar"
                                                                         src="{{ url_for('static', filename='images/d41d8cd98f00b204e9800998ecf8427e.png') }}"
                                                                         alt="gravatar头像"/>
                                    </div>
                                    <p class="input-row">
                                        <i class="row-icon"></i>
                                        <textarea class="text_area" rows="3" cols="80" name="comment" id="comment"
                                                  tabindex="4" placeholder="你不说两句吗？(°∀°)ﾉ……" required></textarea>
                                        <input type="submit" name="submit" class="button" id="submit" tabindex="5"
                                               value="发送"/>
                                    </p>
                                </div>

                                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                            </form>
                        </div>

                        <div id="comments-list-title"><span>{{ comment_nums }}</span> 条评论</div>
                        <div id="loading-comments">
                            <div class="host">
                                <div class="loading loading-0"></div>
                                <div class="loading loading-1"></div>
                                <div class="loading loading-2"></div>
                            </div>
                        </div>
                         <ul class="commentwrap">
                            {% for msg in all_comments %}
                                <li class="comment even thread-even depth-1" id="li-comment-">
                                    <div id="comment-936" class="comment_body contents">
                                        <div class="profile">
                                            <a href=""><img
                                                    src="{{ url_for('static', filename='user_images/'+msg.head_image) }}"
                                                    class="gravatar" alt="{{ msg.nick_name }}"></a>
                                        </div>
                                        <div class="main shadow">
                                            <div class="commentinfo">
                                                <section class="commeta">
                                                    <div class="shang">
                                                        <h4 class="author"><a href="" target="_blank"><img
                                                                src="{{ url_for('static', filename='user_images/'+msg.head_image) }}"
                                                                class="gravatarsmall"
                                                                alt="{{ msg.nick_name }}">{{ msg.nick_name }}</a></h4>
                                                    </div>
                                                </section>
                                            </div>
                                            <div class="body">
                                                <p>{{ msg.content }}</p>
                                            </div>
                                            <div class="xia info">
                                                <span><time datetime="2018-01-16">{{ msg.add_time }}</time></span>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            {% endfor %}

                        </ul>
                        <nav id="comments-navi">

                        </nav>

                    </div>
                </section>
            </div>
        </div>
        <svg id="dwTriangleColor" width="100%" height="40" viewBox="0 0 100 102" preserveAspectRatio="none">
            <path d="M0 0 L50 100 L100 0 Z"></path>
        </svg>
        <div class="wrapper">
        </div>
    </div>

    <div class="navpost-part">
        <div id="NextPrevPosts" style="display: block;">
            {% if prev_article %}
                <div class="prev aos-init aos-animate" data-aos="slide-right" data-aos-delay="1.5s">
                    <div class="arrow"><i class="iconfont"></i></div>
                    <a href="{{ url_for('home.detail') }}?article={{ prev_article.id }}">
                        <div class="preview">
                            <div class="pull-left featuredImg"
                                 style="background-image:url({{ url_for('static', filename='uploads/'+prev_article.image) }});">
                            </div>
                            <a href="{{ url_for('home.detail') }}?article={{ prev_article.id }}"
                               class="pull-left preview-content bold"
                            ><span>上一篇:{{ prev_article.title }}</span></a>
                        </div>
                    </a>
                </div>
            {% endif %}
            {% if next_article %}
                <div class="next aos-init aos-animate" data-aos="slide-left" data-aos-delay="1.5s">
                    <div class="arrow"><i class="iconfont"></i></div>
                    <a href="{{ url_for('home.detail') }}?article={{ next_article.id }}">
                        <div class="preview">
                            <div class="pull-right featuredImg"
                                 style="background-image:url({{ url_for('static', filename='uploads/'+next_article.image) }});"></div>
                            <a href="{{ url_for('home.detail') }}?article={{ next_article.id }}"
                               class="pull-right preview-content bold"
                            ><span>下一篇:{{ next_article.title }}</span></a>
                        </div>
                    </a>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}




app/templates/home/index.html
{% extends "home/base.html" %}
{% import 'utils_template/page.html' as home_page %}

{% block title %}
    主页 - Panson的博客
{% endblock %}

{% block content %}
    <div id="main" class="content">
        <div class="container">
            <article itemscope="itemscope">
                <div class="posts-list js-posts">

                    {% for data in all_articles.items %}
                        {% if loop.index%3 == 0 %}
                            <div class="post post-layout-list js-gallery aos-init aos-animate" data-aos="fade-up">
                            <div class="post-album">
                                <div class="row content">
                                    <div class="bg"
                                         style="background-image: url({{ url_for('static', filename='uploads/'+data.image) }});"></div>
                                    <div class="contentext flex-xs-middle">
                                        <div class="album-title">
                                            <a href="{{ url_for('home.detail') }}?article={{ data.id }}">{{ data.title }}</a>
                                        </div>
                                        <h5 class="review-item-creator"><b>发布日期：</b>{{ data.add_time }}</h5>
                                        <div class="album-content">{{ data.summary }}
                                             <div style="padding: 20px">
                                                    <span class="total-comments-on-post pull-right">
                                                        <a class="gaz-btn primary"
                                                           href="{{ url_for('home.detail') }}?article={{ data.id }}">更 多</a>
                                                    </span>
                                        </div>
                                        </div>

                                    </div>
                                    <div class="album-thumb-width flex-xs-middle">

                                    </div>
                                </div>
                            </div>
                              </div>
                        {% else %}
                            {% if loop.index%2 == 0 %}
                                <div class="post post-layout-list" data-aos="fade-up">
                                    <div class="postnormal review ">
                                        <div class="post-container review-item">
                                            <div class="row review-item-wrapper">
                                                <div class="col-sm-3">
                                                    <a rel="nofollow" href="detail.html">
                                                        <div class="review-item-img"
                                                             style="background-image: url({{ url_for('static', filename='uploads/'+data.image) }});"></div>
                                                    </a>
                                                </div>
                                                <div class="col-sm-9 flex-xs-middle">

                                                    <div class="review-item-title" style="padding-top:20px;">
                                                        <a href="{{ url_for('home.detail') }}?article={{ data.id }}"
                                                           rel="bookmark">{{ data.title }}</a>
                                                    </div>

                                                    <div class="review-item-creator"><b>发布日期：</b>{{ data.add_time }}
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="review-bg-wrapper">
                                                <div class="bg-blur"
                                                     style="background-image: url({{ url_for('static', filename='uploads/'+data.image) }});"></div>
                                            </div>
                                        </div>
                                        <div class="post-container">
                                            <div class="entry-content">{{ data.summary }}...
                                            </div>
                                                <span class="total-comments-on-post pull-right">
                                                    <a class="gaz-btn primary" href="{{ url_for('home.detail') }}?article={{ data.id }}">更 多</a>
                                                </span>

                                        </div>
                                    </div>
                                </div>
                            {% else %}

                                <div class="post post-layout-list" data-aos="fade-up">
                                    <div class="status_list_item icon_kyubo">
                                        <div class="status_user"
                                             style="background-image: url({{ url_for('static', filename='uploads/'+data.image) }});">
                                            <div class="status_section">
                                                <a href="{{ url_for('home.detail') }}?article={{ data.id }}"
                                                   class="status_btn">{{ data.title }}</a>
                                                <h5 class="review-item-creator"><b>发布日期：</b>{{ data.add_time }}</h5>
                                                <p class="section_p">{{ data.summary }}... </p>
                                                <div style="padding: 20px">
                                                    <span class="total-comments-on-post pull-right">
                                                        <a class="gaz-btn primary"
                                                           href="{{ url_for('home.detail') }}?article={{ data.id }}">更 多</a>
                                                    </span>

                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            {% endif %}

                        {% endif %}
                    {% endfor %}

                    </div>

             <!-- -pagination  -->
            {{ home_page.page(all_articles, 'home.index') }}
            </article>
        </div>
    </div>
{% endblock %}